### ISSUE TITLE
Incorporate mapf export

### ISSUE THREAD

**Issue by shayanaimi** [nirgreshler/natnet-motionclient#2]
I think this will come in the form of a few additional functions and properties in Visualizer. Can also pull this from my old code (might be on my laptop). 

Goal: export the position data in the form of a mapf file (with . and @) either in real-time or at request. 

Question for @nirgreshler : now that we can sense both robots and obstacles should we have different symbols for them? Do you only care about obstacles or robots too?

**Comment by nirgreshler** [comment]
The .map file we're generating represents the environment itself, not robots.
For that, there is another file (.scen) for representing a single MAPF scenario, with the start and goal locations of each robot.
Therefore, for generating the environment file, we only need to account for obstacles.
We'll later do the scenario file as well.

**Comment by shayanaimi** [comment]
Done. See Grid.py

**Comment by shayanaimi** [comment]
Done. See Grid.py
